### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by DaP1A** [ChenHongruixuan/MambaCD#13]
我想问一下dataset数据集的时候，SCD数据集SECOND里面的GT_CD源数据集没有啊。是要自己生成吗？

**Comment by ChenHongruixuan** [comment]
是的，直接做一个简单的比较操作就可以了。我更新一下README文件。

**Comment by DaP1A** [comment]
> 是的，直接做一个简单的比较操作就可以了。我更新一下README文件。

谢谢
