### ISSUE TITLE
amazing Project, I want to visualize a binary graph of the output image as an evaluation, what should I do

### ISSUE THREAD

**Issue by ljbddy** [ChenHongruixuan/MambaCD#14]

**Comment by ChenHongruixuan** [comment]
Hi, 

Thank you so much! I mentioned this in README file. Please kindly take a look. Here is a direct [link](https://github.com/ChenHongruixuan/MambaCD?tab=readme-ov-file#e-inference-using-our-weights). 


Best,

**Comment by ljbddy** [comment]
@ChenHongruixuan Thank you for your answer, but I still haven't found the part that can output visual images. Which part is he in? Is he Inference Using Our Weights

**Comment by ChenHongruixuan** [comment]
Hi,

The INFERECE code automatically saves the detection results.

Please see 110-114 lines. 

Best,
