### ISSUE TITLE
something about "infer_MambaBCD.py"

### ISSUE THREAD

**Issue by COUJIALUO** [ChenHongruixuan/MambaCD#15]
"Hello, I would like to use the SCD model for prediction, but I only see 'infer_MambaBCD.py' available. Will there be an update to include 'infer_MambaSCD.py'? Thank you very much."

**Comment by ChenHongruixuan** [comment]
Hi,

We have uploaded the code for inference on the SECOND dataset. Please kindly check that. @COUJIALUO 

Best,
