### ISSUE TITLE
how to resume train?

### ISSUE THREAD

**Issue by regainOWO** [ChenHongruixuan/MambaCD#16]
I want to continue my unfinished model training, how to ressume train

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your question. Just like the inference part, utilizing the --resume to load the saved model at the beginning. 

Best,

**Comment by regainOWO** [comment]
thanks for your replay! but i found --resume param just load the previous trained model, the training progress bar starts from zero , not start with the progress of the previous training

**Comment by ChenHongruixuan** [comment]
Hi,

The progress bar just visually shows the training progress. It's perfectly possible for yourself to set a new parameter start_iter if you want to. Yet in any case, the weights of your previously trained model are already loaded and can continue to be trained.

Best,
