### ISSUE TITLE
Request for Trained Weights on xBD Dataset from ChangeMamba Project

### ISSUE THREAD

**Issue by XCZhou520** [ChenHongruixuan/MambaCD#2]
Hello,

I am highly interested in your work on "ChangeMamba: Remote Sensing Change Detection with Spatio-Temporal State Space Model" posted on GitHub. I noticed that you have successfully trained the MambaBDA model on the xBD dataset and achieved remarkable results. I am currently engaged in related research and would greatly appreciate the opportunity to test my dataset using your trained weights.

Would it be possible for you to share the weights trained on the xBD dataset? It would be immensely beneficial for my research, and I will ensure to acknowledge and thank your work in my subsequent studies.

Thank you very much for your consideration and assistance!

Best regards,

xczhou

**Comment by ChenHongruixuan** [comment]
Hi Zhou,

Many thanks for your interset to our work! The repo is still being updated. The weights of MambaBDA are expected to be released next week! We'd appreciate that if you could stay tuned.

Best,
Hongruxiuan Chen

**Comment by ChenHongruixuan** [comment]
Hi Zhou,

We have uploaded the retrained weight of MambaBDA-Tiny with 81.11% oaF1. You are welcome to use it in your own research and applications. 

Best,
Hongruixuan
