### ISSUE TITLE
Regarding the handling of semantic labels in semantic change detection tasks.

### ISSUE THREAD

**Issue by ZHONIN** [ChenHongruixuan/MambaCD#20]
Thank you for sharing your excellent work. And umm, is there a problem with the areas highlighted in red in the image? I think that both label_1 and label_2 are three-channel images, why are they being processed as single-channel images here?
![image](https://github.com/ChenHongruixuan/MambaCD/assets/48908326/036a208a-9cdb-483c-9d4e-cd0608eb19f7)

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your question! SECOND dataset provides labels in RGB 3-channel for easy visualisation. But in the actual training process, you need to convert them to single channel with values 0-6. 

Best,

**Comment by ZHONIN** [comment]
Thanks for your reply ~
