### ISSUE TITLE
make_data_loader.py

### ISSUE THREAD

**Issue by XiaoBaiHhy** [ChenHongruixuan/MambaCD#21]
Hello, when I only run the BDA task, in the xBD dataset I downloaded, the train folder only contains the images, targets and labels three files, and then I try to change it to the format in the make_data_loader.py of your paper, but it is always wrong, how did you change this part of the code, is there any changed code to provide it, thank you very much!

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your question. May I ask you to provide me with the specific error information? 

Best,

**Comment by XiaoBaiHhy** [comment]
![2024-04-29 11-09-12 的屏幕截图](https://github.com/ChenHongruixuan/MambaCD/assets/152368713/9203cd85-38dd-4299-9d28-11817c93e187)

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you very much for your question. It depends on the channel of your label, in our previous experiments the generated labels were three channel, so we only took one of the channels. But for the officially provided label, it is already single channel, so it can be used directly without the above operation. 

Also, the issue in Trainer has been fixed. Please kindly check that. 

Best,
