### ISSUE TITLE
在SECOND数据集上训练MambaSCD出现的问题

### ISSUE THREAD

**Issue by YonghuiTAN22** [ChenHongruixuan/MambaCD#22]
当进入imutils.py脚本中的random_crop_mcd时，似乎变化前和变化后的标签维度是(512, 512, 3)，而在这个方法中将其维度视作(512, 512)，这样就会导致维度对应不上，请问应该如何修改呢

**Comment by ChenHongruixuan** [comment]
Hi,

Many thanks for your interest to our work! 

Please Refer to the Data Preparation section of the README file:
> Note that the land-cover maps are RGB images in the original SECOND dataset for visualization, you need to transform them into single-channel. Also, the binary change maps should be generated by yourself and put them into folder [GT_CD].

Best,

**Comment by tyh153** [comment]
Thanks for your answer,

I have noticed the corresponding data preprocessing section in README.md and have successfully solved this problem.

Best regards

**Comment by ChenHongruixuan** [comment]
Great! Glad to hear that. 

Best,
