### ISSUE TITLE
BCD加载预预训练权重与当前模型不匹配

### ISSUE THREAD

**Issue by pingcong** [ChenHongruixuan/MambaCD#23]
loading mdel...
Successfully load ckpt /root/pingcc/MambaCD/pretrained_weight/vssm_tiny_0230_ckpt_epoch_262.pth
_IncompatibleKeys(missing_keys=['outnorm0.weight', 'outnorm0.bias', 'outnorm1.weight', 'outnorm1.bias', 'outnorm2.weight', 'outnorm2.bias', 'outnorm3.weight', 'outnorm3.bias'], unexpected_keys=['classifier.norm.weight', 'classifier.norm.bias', 'classifier.head.weight', 'classifier.head.bias', 'layers.2.blocks.4.norm.weight', 'layers.2.blocks.4.norm.bias', 'layers.2.blocks.4.op.x_proj_weight', 'layers.2.blocks.4.op.dt_projs_weight', 'layers.2.blocks.4.op.dt_projs_bias', 'layers.2.blocks.4.op.A_logs', 'layers.2.blocks.4.op.Ds', 'layers.2.blocks.4.op.out_norm.weight', 'layers.2.blocks.4.op.out_norm.bias', 'layers.2.blocks.4.op.in_proj.weight', 'layers.2.blocks.4.op.conv2d.weight', 'layers.2.blocks.4.op.out_proj.weight', 'layers.2.blocks.4.norm2.weight', 'layers.2.blocks.4.norm2.bias', 'layers.2.blocks.4.mlp.fc1.weight', 'layers.2.blocks.4.mlp.fc1.bias', 'layers.2.blocks.4.mlp.fc2.weight', 'layers.2.blocks.4.mlp.fc2.bias'])
Backbone_VSSM load_pretrained

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your interest to our work. 

This warning came up during our training process as well. But it doesn't matter, just start your training process straight away.

Best,

**Comment by pingcong** [comment]
我这边是在采用预训练的权重在公开数据集SYSU上进行复现，现在测出来的精度就很差，不知道问题出在哪里。_IncompatibleKeys(missing_keys=['outnorm0.weight', 'outnorm0.bias', 'outnorm1.weight', 'outnorm1.bias', 'outnorm2.weight', 'outnorm2.bias', 'outnorm3.weight', 'outnorm3.bias'], unexpected_keys=['classifier.norm.weight', 'classifier.norm.bias', 'classifier.head.weight', 'classifier.head.bias'])
Backbone_VSSM load_pretrained
Racall rate is 0.9930704898446834, Precision rate is 0.2644312596433741, OA is 0.2926177978515625, F1 score is 0.41765171404524737, IoU is 0.2639442389216138, Kappa coefficient is 0.023825750047458225
