### ISSUE TITLE
MambaSCD训练时出现错误grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by regainOWO** [ChenHongruixuan/MambaCD#26]
我发现在自己的数据集上训练MambaSCD时，计算lovasz_softmax会返回一个空的列表，我发先标签文件都是背景，这个有什么办法解决吗？数据集当中不能有负样本吗？
![image](https://github.com/ChenHongruixuan/MambaCD/assets/54225410/939f28fb-a2e2-4d72-be10-e98e7749f01d)

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your question. You are training on your own SCD dataset, not SECOND right? Then you need to keep the dataset in the same format as the SECOND dataset. Also, I would like to remind you that in the land cover map in the SECOND dataset, class 0 is the background class, is it the same for your dataset?

Best,

**Comment by regainOWO** [comment]
用的是自己的数据集；格式和SECOND的格式是一致的；标签中背景是0；

**Comment by ChenHongruixuan** [comment]
Hi,

Could you try removing the lovasz loss and see the situation? Everything works fine with the current code on the SECOND dataset. However, other datasets may have problems, I haven't tested it on other SCD datasets.

Best,

**Comment by ChenHongruixuan** [comment]
Hi,

May I ask if you have solved this problem?

Best,

**Comment by regainOWO** [comment]
> Hi,
> 
> Could you try removing the lovasz loss and see the situation? Everything works fine with the current code on the SECOND dataset. However, other datasets may have problems, I haven't tested it on other SCD datasets.
> 
> Best,

@ChenHongruixuan i changed loss, now it works fine!

**Comment by Buddhi19** [comment]
Hi @ChenHongruixuan ,
I got the same issue but when working with the SECOND dataset you have provided,
![image](https://github.com/user-attachments/assets/dc617004-52a4-4937-aa82-703bf73ace3f)
removing the lovasz loss solved it but this will have a impact on the results?

**Comment by ChenHongruixuan** [comment]
Hi @

**Comment by Buddhi19** [comment]
Hi @ChenHongruixuan ,
Thank you, that solved the issue.

Cheers,
