### ISSUE TITLE
语义变化检测second的权重能否提供一下？或者提供一下数据处理脚本，谢谢！

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [ChenHongruixuan/MambaCD#28]
如题，我是语义检测方面的初学者，我不明白如何生成Binary change map~~非常感谢

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your question and your interest to our work. You can just write python scripts to compare the labels of the SECOND dataset and you'll get the change labels.

Best,

**Comment by regainOWO** [comment]
@ChenHongruixuan 我觉得可以直接在dataset中添加这部分，这样就不需要额外再生成Binary change map文件了

**Comment by ChenHongruixuan** [comment]
Thank you for the suggestion. We will consider that in next update.
