### ISSUE TITLE
SiameseKPConv 和MambaCD对比

### ISSUE THREAD

**Issue by pingcong** [ChenHongruixuan/MambaCD#29]
非常感谢您的指导，成功复现MambaCD而且在2D变化检测达到sota，因为自己刚接触这块领域，关注到在3D提出了SiameseKPConv ，不知道是否针对这两个模型进行过对比呢

**Comment by ChenHongruixuan** [comment]
Thank you again for your interest in our work, as well as being glad you reproduced our accuracy.

Note that SiameseKPConv is for 3D change detection, which is very different from 2D change detection. Therefore ChangeMamba and SiameseKPConv are not comparable. However, you can try to apply the Mamba model to 3D change detection.

Best,

**Comment by pingcong** [comment]
的确，这也是一个非常不错的想法，ChangeMamba应用于三维变化检测之前有相关的验证码

**Comment by ChenHongruixuan** [comment]
Hi,

If you are talking about change detection of 3D point cloud data, then no. Note that point cloud data and remote sensing image data are very different.
