### ISSUE TITLE
dataset category

### ISSUE THREAD

**Issue by wwjwy** [ChenHongruixuan/MambaCD#3]
Hello,
I'm very interested in your work and I have some questions for you while reading the code. Regarding the data set categories used in the article and the number of categories in the ADE data set, and I see that the number of categories in the code is also 150, do I need to change the type and number of categories in other locations when using it?
Thanks!

**Comment by ChenHongruixuan** [comment]
Hi,
Thank you so much for your interset to our work! The folder <segmentation> is the legacy from vmamba. Please just take look at the folder <changedetection>, where the all code of our methods is located.

Best,
