### ISSUE TITLE
SCD pretrained weights

### ISSUE THREAD

**Issue by CFOP-xyn** [ChenHongruixuan/MambaCD#30]
Hi, I am very interested in this awesome job. I've been doing some work related to semantic change detection recently and I'd like to use your pretrained weights to train on my dataset. Can you please provide me the weights for the semantic change detection model?

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your interest to our work! The weights of MambaSCD and MambaBDA will be released after the manuscript is accepted. 

Besides, if you want to train MambaSCD model on your own dataset, I assume our weights are unnecessary. You can directly perform our code. 

Best,

**Comment by CFOP-xyn** [comment]
Thank you very much for your reply, I will try to use your SCD model for training on my dataset!

**Comment by liuxuanguang** [comment]
> Thank you very much for your reply, I will try to use your SCD model for training on my dataset!

你好！你在SECOND上复现的Mamba-SCD精度如何呢？在自己的数据集上的精度又能达到多少呢？

**Comment by liuxuanguang** [comment]
> Thank you very much for your reply, I will try to use your SCD model for training on my dataset!

你好！你在SECOND上复现的Mamba-SCD精度如何呢？在自己的数据集上的精度又能达到多少呢？
