### ISSUE TITLE
cpu inference

### ISSUE THREAD

**Issue by regainOWO** [ChenHongruixuan/MambaCD#33]
我发现模型的forward和backward都依赖了selective_scan，我想将训练好的模型迁移到没有nvidia gpu的设备上运行，但selective_scan需要有cuda能完成安装，selective_scan有cpu或者pytorch的实现吗？

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your question! The selective_scan is based on Mamba and VMamba repo. Maybe you can refer to the repo and their issues to see if there are any solutions for your case.

Best,
