### ISSUE TITLE
validation dataset cropsize

### ISSUE THREAD

**Issue by Jiaxzhao** [ChenHongruixuan/MambaCD#34]
Thank you very much for your efforts. I have observed that while running train_MambaSCD.py, the dataset size during the validation stage was not cropped. I would like to inquire about the data processing procedures employed during the validation phase.

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your question. During the training phase, the image is randomly cropped to 256x256 (of course you can crop it ahead) as well as some other data augmentation methods are applied. During the testing phase, the network infer the results directly on the images with original size without cropping.

Best,
