### ISSUE TITLE
在SECOND数据集上的复现精度较低

### ISSUE THREAD

**Issue by liuxuanguang** [ChenHongruixuan/MambaCD#36]
作者您好，感谢分享这份工作！但我在复现MambaSCD_small在SECOND数据集上的实验时，达不到原文中提供的精度指标，sek只有16。超参数均按照原文提供的数值而设置，但在加载预训练权重时，显示：
Successfully load ckpt MambaCD-master/pretrained_weight/vssm_small_0229_ckpt_epoch_222.pth
_IncompatibleKeys(missing_keys=['outnorm0.weight', 'outnorm0.bias', 'outnorm1.weight', 'outnorm1.bias', 'outnorm2.weight', 'outnorm2.bias', 'outnorm3.weight', 'outnorm3.bias'], unexpected_keys=['classifier.norm.weight', 'classifier.norm.bias', 'classifier.head.weight', 'classifier.head.bias'])
能否提供完整预训练权重呢？期待您的回复，十分感谢！

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your interest to our work. The remaining weights will be released after the paper is accepted. The paper has been revised and now is under the re-review stage. We hope you can keep tuned and appreciate your patience. 

Best,
