### ISSUE TITLE
The third layer of the network in the BCD task

### ISSUE THREAD

**Issue by absqh** [ChenHongruixuan/MambaCD#39]
![1719302746976](https://github.com/ChenHongruixuan/MambaCD/assets/104881403/d219ad60-b4f5-4d96-a9ff-9fa106dea24a)
Hello, I noticed that the number of layers of the small model introduced in the paper are (2, 2, 27, 2)，But the configuration file of small is (2, 2, 15, 2)，Do I need to modify the configuration file?
![1](https://github.com/ChenHongruixuan/MambaCD/assets/104881403/72a57d27-c332-4768-9a91-9295255a4d3e)

**Comment by ChenHongruixuan** [comment]
Hi, thank you for your question. Please just use the configuration file we uploaded. No need to modify it. 

Best,
