### ISSUE TITLE
CUDA version requirements

### ISSUE THREAD

**Issue by bregesyn** [ChenHongruixuan/MambaCD#4]
hello！

First of all, I'd like to express my sincere thanks for your great work on the MambaCD project. This project has been of great help to my research and work, for which I am very appreciative and grateful.

While trying to install and use the project, I noticed that the installation process requires a CUDA version of at least 11.6. Due to hardware and other dependency limitations, the CUDA version installed in my environment can only be up to 11.4.

Therefore, I would like to ask a few questions:
1. Does the project absolutely require CUDA 11.6 and above to run properly?
2. Do you have a suggested solution or alternative for environments that only support CUDA 11.4? For example, is it possible to modify the configuration or source code to be compatible with CUDA 11.4?
3. If the code needs to be adjusted to support CUDA 11.4, can you provide some advice or guidance to help me achieve this?

I'd really like to have this work successfully in my environment. Any advice and help on how to resolve this compatibility issue would be extremely valuable and appreciated.

Very much looking forward to your reply！

best wishes！

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your interest to our work! 

We have encountered the problem you mentioned before. The problem mainly stems from the environment configuration requirements of VMamba. However, our solution is to upgrade CUDA, and currently our CUDA version is 12.1. Regarding whether versions lower than 11.6 are able to run the code, we are sorry that we don't have any conclusions yet, and we suggest that you can go to the issue in the vmamba repo to see if there is any relevant solution.

If there are any other questions we can help, feel free to leave a comment.

Best,
