### ISSUE TITLE
cd kernels/selective_scan && pip install .  ERROR

### ISSUE THREAD

**Issue by SPWUSY** [ChenHongruixuan/MambaCD#41]
error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]

      torch.__version__  = 1.13.0+cu117

      CUDA_HOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7

      running bdist_wheel
      running build
      running build_ext
      C:\Users\SY\.conda\envs\cd\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'selective_scan_cuda_core' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: Could not build wheels for selective_scan, which is required to install pyproject.toml-based projects

**Comment by ChenHongruixuan** [comment]
Hi,

Please note that the operating system requirement for this repo is LINUX.

Best,

**Comment by SPWUSY** [comment]
> Hi,
> 
> Please note that the operating system requirement for this repo is LINUX.
> 
> Best,

Mine is windows,do you have some measures?
However,thanks very much

**Comment by ChenHongruixuan** [comment]
Hi,

As far as I know, this repo can only be run on Linux now. You can consider Virtual machine. But If I remember correctly, you can also install Linux system on windows. 

Best,
