### ISSUE TITLE
I want to slightly restructure the model, what can I do

### ISSUE THREAD

**Issue by ljbddy** [ChenHongruixuan/MambaCD#44]
Hello, I have used your model and got good results, but I want to modify the model structure, such as adding a module in the encoder or decoder part. May I ask which py file is your model structure defined in

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your question. The model structure defined in the following two folders: 
https://github.com/ChenHongruixuan/MambaCD/tree/master/changedetection/models
https://github.com/ChenHongruixuan/MambaCD/tree/master/classification/models

Best,

**Comment by ljbddy** [comment]
Thank you. What should I do if I want to add some negative samples to the model? Is this requirement easy to implement

**Comment by ChenHongruixuan** [comment]
Hi, What do you mean about negative samples? Does it mean that all pixels are unchanged pixels? You can achieve this by adjusting crop_size.
