### ISSUE TITLE
datasets resolution ratio

### ISSUE THREAD

**Issue by lin-ovvo1111** [ChenHongruixuan/MambaCD#46]
作者你好，使用LEVIR-CD+数据集处理成规定格式时，图像的分辨率是全部是1024x1024还是全部都是256x256或者保留这两种分辨率的

**Comment by ChenHongruixuan** [comment]
Hi,

This depends on the size of your GPU memory. If you have a large GPU memory you can keep it at 1024x1024, otherwise you can crop it to 256x256.

Best
