### ISSUE TITLE
Use our own pre-trained weights

### ISSUE THREAD

**Issue by absqh** [ChenHongruixuan/MambaCD#47]
If I want to use the weights trained on this model as my own pre-trained weights, how can I use them?
![1720680397854](https://github.com/ChenHongruixuan/MambaCD/assets/104881403/86785fdd-ac9d-4eaf-88ad-8a22beb87893)

**Comment by ChenHongruixuan** [comment]
Hi, 

Please use the --resume to load your weight. You can check the README file.

Best
