### ISSUE TITLE
Failed form /XX/projects/MambaCD/10500_model.pth: 'model'

### ISSUE THREAD

**Issue by hejun888** [ChenHongruixuan/MambaCD#49]
![1721294002253](https://github.com/user-attachments/assets/59bc3654-70cc-4363-89ee-6e4a7d3e7709)
![1721293942196](https://github.com/user-attachments/assets/4d9568a5-c1b2-43db-b15c-e6a9209cc07a)
Failed form /XX/projects/MambaCD/10500_model.pth: 'model',发生这种错误，请教下

**Comment by absqh** [comment]
你好，我想请问一下这个你是怎么解决的？
