### ISSUE TITLE
Spatio-temporal relationship learning methods of ChangeMamba Code

### ISSUE THREAD

**Issue by ABCnutter** [ChenHongruixuan/MambaCD#5]
Hello, where is the code for the "Spatio-temporal relationship learning methods of ChangeMamba" section? I didn't find it. Thanks.

**Comment by ABCnutter** [comment]
I would like to find the part of the code that differs from the vmamba source code in the scanning method section of your paper. Thank you.

**Comment by absqh** [comment]
你好，是在changedecode里边吗？

**Comment by ABCnutter** [comment]
yeah



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月28日 10:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [ChenHongruixuan/MambaCD] Spatio-temporal relationship learning methods of ChangeMamba Code (Issue #5) |

你好，是在changedecode里边吗？
