### ISSUE TITLE
Questions about the calculation of evaluation indices(IOU)

### ISSUE THREAD

**Issue by wujiang0156** [ChenHongruixuan/MambaCD#50]
Thank you very much, your work is very meaningful, but I have some questions. Thank you.
![image](https://github.com/user-attachments/assets/b7fccf3e-242e-4831-8dae-ceceb98ede2f)
In the table above, is the IoU of the foreground （building）change class?
But in your code, IoU is calculated like this
![image](https://github.com/user-attachments/assets/092848b3-b7bc-4135-993b-26b4424f8a31)
It doesn't seem to be the IoU of the foreground change class (building),  **Here it might be minus self.confusion_matrix[1, 1]) instead of adding self.confusion_matrix[1, 1]).**

**Comment by ChenHongruixuan** [comment]
Please review the definition of IoU. It is [IoU = TP / (TP + FP + FN)]. 

I don't understand what do you mean about > This is a serious error, please provide a solution?

**Comment by ChenHongruixuan** [comment]
About the calculation of mIoU, it is also write. You can review the definition of mIoU and calculate it yourself manually, in comparison with using our code.

**Comment by wujiang0156** [comment]
> About the calculation of mIoU, it is also right. You can review the definition of mIoU and calculate it yourself manually, in comparison with using our code.
![image](https://github.com/user-attachments/assets/9f7bcab5-4ee6-4b91-a0a7-0229ff37ca93)
The calculation method of mIoU is correct
What I mean is that when calculating IoU, it should be subtraction instead of addition here.

**Comment by wujiang0156** [comment]
> Thank you for your question. Please review the definition of IoU. It is [IoU = TP / (TP + FP + FN)].
> 
> I don't understand what do you mean about > This is a serious error, please provide a solution?
The formula is correct, but there is a problem with the code.
What I mean is that when calculating IoU, it should be subtraction instead of addition here.

**Comment by wujiang0156** [comment]
> About the calculation of mIoU, it is also right. You can review the definition of mIoU and calculate it yourself manually, in comparison with using our code.
> self.confusion_matrix[1, 1])

Thank you for your response.
miou 和 iou 的计算方式是类似的，都是通过混淆矩阵计算得到的，不同的是miou 是累加的。因此代码在计算IOU时应该时减去self.confusion_matrix[1, 1])而不是加self.confusion_matrix[1, 1])

IoU should be calculated as follows:
![image](https://github.com/user-attachments/assets/95302c97-6896-4858-9045-0ddd39a14d19)

**Comment by ChenHongruixuan** [comment]
I think you didn't figure out the concept of IoU here. When calcualting IoU for binary change detection, the num_class is 2. The size of confusion matrix is 2x2, where self.confusion_matrix[1,1] is TP, the remaning two terms are FP and FN. Therefore, according to the definition of IoU=TP / (TP + FN + FP), the code should be self.confusion_matrix[1,1] / (self.confusion_matrix[1,0] + self.confusion_matrix[1,0] + self.confusion_matrix[1,1]). The accumulation does not exist here. 

BTW, I think the more appropriate way about raising issue is that you should try to calculate them yourself and then use the wording like [ciritial error].

**Comment by wujiang0156** [comment]
> I think you didn't figure out the concept of IoU here. When calcualting IoU for binary change detection, the num_class is 2. The size of confusion matrix is 2x2, where self.confusion_matrix[1,1] is TP, the remaning two terms are FP and FN. Therefore, according to the definition of IoU=TP / (TP + FN + FP), the code should be self.confusion_matrix[1,1] / (self.confusion_matrix[1,0] + self.confusion_matrix[1,0] + self.confusion_matrix[1,1]). The accumulation does not exist here.
> 
> BTW, I think the more appropriate way about raising issue is that you should try to calculate them yourself and then use the wording like [ciritial error].

Thank you for your response.
![image](https://github.com/user-attachments/assets/22824aec-d813-4c54-a6a4-7f747b80d8ef)
So you mean that when calculating mIoU, addition should also be used, but the code here uses subtraction. How can this be explained?
![image](https://github.com/user-attachments/assets/241783fd-e5b3-4c60-a9d2-ecf6d6dbfb9c)

**Comment by wujiang0156** [comment]
> I think you didn't figure out the concept of IoU here. When calcualting IoU for binary change detection, the num_class is 2. The size of confusion matrix is 2x2, where self.confusion_matrix[1,1] is TP, the remaning two terms are FP and FN. Therefore, according to the definition of IoU=TP / (TP + FN + FP), the code should be self.confusion_matrix[1,1] / (self.confusion_matrix[1,0] + self.confusion_matrix[1,0] + self.confusion_matrix[1,1]). The accumulation does not exist here.
> 
> BTW, I think the more appropriate way about raising issue is that you should try to calculate them yourself and then use the wording like

Thank you for your response.

yes , you are right.  
FP = np.sum(self.confusion_matrix, axis=0) - TP 
FN = np.sum(self.confusion_matrix, axis=1) - TP  
 so , When calculating mIoU, it should be +TP.

Thank you for your patient explanations. Your work has been very inspiring to me. Thanks again for your efforts.

**Comment by JTRNEO** [comment]
For mIoU, when summing over rows and columns to get the total predicted and actual areas for each class, True Positive gets counted twice (once in the row sum and once in the column sum). Therefore, we subtract True Positive once to correct this over-count. Please note that the code for calculating mIoU and IoU based on the confusion matrix is not exactly the same. You may try using the calculation methods from official libraries or your own methods to verify consistency with our evaluation code.

**Comment by wujiang0156** [comment]
> For mIoU, when summing over rows and columns to get the total predicted and actual areas for each class, True Positive gets counted twice (once in the row sum and once in the column sum). Therefore, we subtract True Positive once to correct this over-count. Please note that the code for calculating mIoU and IoU based on the confusion matrix is not exactly the same. You may try using the calculation methods from official libraries or your own methods to verify consistency with our evaluation code.

It's like this, you are too kind, thank you very much!

**Comment by ChenHongruixuan** [comment]
It's glad to hear that your question has been solved! Thank you again for your interest to our work :)
