### ISSUE TITLE
在SYSU数据集上测验mambaBCD结果有误

### ISSUE THREAD

**Issue by YoushouldknowGQL** [ChenHongruixuan/MambaCD#53]
python3 /mnt/c/Users/admin/MambaCD/changedetection/script/infer_MambaBCD.py \
    --dataset 'SYSU' \
    --model_type 'MambaBCD_Small' \
    --test_dataset_path '/mnt/e/SYSU-CD/SYSU-CD/test' \
    --test_data_list_path '/mnt/e/SYSU-CD/SYSU-CD/test.txt' \
    --cfg '/mnt/c/Users/admin/MambaCD/changedetection/configs/vssm1/vssm_small_224.yaml' \
    --resume '/mnt/d/weights/MambaBCD_Small_SYSU_F1_0.8336.pth' \
    --result_saved_path '/mnt/c/Users/admin/MambaCD/results'
在 SYSU 数据集上使用训练完成的 MambaBCD-Small推断二元变化图，结果显示Racall rate is nan, Precision rate is nan, OA is nan, F1 score is nan, IoU is nan, Kappa coefficient is nan
Inference stage is done!

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your question! Could you give us more detail about the print results from the running code? Also, please take a look at that the generated binary change maps are valid or not. They can help us figure out the specific issue.

Best,

**Comment by YoushouldknowGQL** [comment]
/mnt/c/Users/admin/MambaCD/changedetection/utils_func/metrics.py:25: RuntimeWarning: invalid value encountered in scalar divide
  Rec = self.confusion_matrix[1, 1] / (self.confusion_matrix[1, 0] + self.confusion_matrix[1, 1])
/mnt/c/Users/admin/MambaCD/changedetection/utils_func/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  Pre = self.confusion_matrix[1, 1] / (self.confusion_matrix[0, 1] + self.confusion_matrix[1, 1])
/mnt/c/Users/admin/MambaCD/changedetection/utils_func/metrics.py:10: RuntimeWarning: invalid value encountered in scalar divide
  Acc = np.diag(self.confusion_matrix).sum() / self.confusion_matrix.sum()
/mnt/c/Users/admin/MambaCD/changedetection/utils_func/metrics.py:58: RuntimeWarning: invalid value encountered in scalar divide
  IoU = self.confusion_matrix[1, 1] / (
/mnt/c/Users/admin/MambaCD/changedetection/utils_func/metrics.py:75: RuntimeWarning: invalid value encountered in scalar divide
  observed_accuracy = np.trace(self.confusion_matrix) / num_total
/mnt/c/Users/admin/MambaCD/changedetection/utils_func/metrics.py:77: RuntimeWarning: invalid value encountered in divide  np.sum(self.confusion_matrix, axis=0) / num_total * np.sum(self.confusion_matrix, axis=1) / num_total)
Racall rate is nan, Precision rate is nan, OA is nan, F1 score is nan, IoU is nan, Kappa coefficient is nan
Inference stage is done!
日志提供的信息显示，在计算指标时，混淆矩阵中存在问题，导致在执行除法运算时分母为零。请问这是什么原因导致的？

**Comment by YoushouldknowGQL** [comment]
It may be an issue with the dataset. May I ask what content needs to be listed in the test. txt document in the dataset file?

**Comment by ChenHongruixuan** [comment]
Hi, 

Please check the following cotents:

- The trained model's weight has been loaded sucessfully or not? 
- The test.txt document only records the name of image file
- Please check the label's value: 255 is change, 0 is non-change. 

Best,

**Comment by YoushouldknowGQL** [comment]
Okay, thank you

**Comment by ChenHongruixuan** [comment]
Okey, keep us posted if you solve the problem :)

**Comment by YoushouldknowGQL** [comment]
Racall rate is 0.8074370200623197, Precision rate is 0.8614169501615304, OA is 0.9239544410705567, F1 score is 0.8335539809709083, IoU is 0.7146099925521876, Kappa coefficient is 0.7843404490614121
Inference stage is done!
Thank you for your help. The problem has been resolved.

**Comment by ChenHongruixuan** [comment]
Hi,

Glad to hear that! 

Could you tell us exactly what is causing this problem so that other peers can refer to it? 

Also, if our code helps you with your research, we'd appreciate it if you could give ChangeMamba a star :)

Best,

**Comment by YoushouldknowGQL** [comment]
The reason is that test.txt does not correctly record the name of the image.
ChangeMamba's change detection performance is very good and deserves a star.
I have already given it 😀

**Comment by ChenHongruixuan** [comment]
Glad to hear that. Thank you so much!
