### ISSUE TITLE
是否预加载VSSM权重会对模型精度有影响

### ISSUE THREAD

**Issue by blacksheeplzu** [ChenHongruixuan/MambaCD#54]
作者你好，文章里模型的效果非常好，但是在复现WHU-CD数据集上进行训练发现预加载vssm_small_0229_ckpt_epoch_222.pth进行训练能够达到文章里的效果，；但是如果选择不使用vssm_small_0229_ckpt_epoch_222.pth权重文件在数据集上训练F1-score会从文章里的94.**变成90.**，请问这是什么原因导致的呢，正常来说在imageNet数据集上训练得到的权重并不适应遥感数据集

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your interest to our work. We assume that pre-trained weights on Imagenet provide a very good initial value compared to if you were to train from scratch. Besides mamba, a similar situation exists with transformer. If you train transfomer from scratch on remote sensing tasks, its accuracy cannot match many CNN networks. 

Your statement that the weights obtained from training on the ImageNet dataset are not adapted to the remote sensing dataset is a bit inaccurate. We can say that the weights obtained by training on the ImageNet dataset may not be as good as the weights obtained by pre-training on some large remote sensing datasets, but we can't say that they are not applicable to remote sensing datasets. Especially for optical high resolution images, the weights obtained by pre-training on ImageNet dataset can be well extracted for features applicable to downstream tasks.

Best,

**Comment by blacksheeplzu** [comment]
Thank you for your answer, it was very helpful in solving my confusion, this article is really awesome.
