### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by sasa550** [ChenHongruixuan/MambaCD#55]
Dear Author, 
could you please let me know the time required to train for 50,000 iterations on the SECOND dataset, as well as the GPU model you used?

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your interest to our work. The GPU we use is NVIDIA A100 and training time of MambaSCD-Small with 50000 iterations on the SECOND dataset is about 19h (Accuracy assessment is performed every 500 iterations).  

Best,

**Comment by sasa550** [comment]
Got it, thank you for your response. Additionally, I would like to ask, what is the memory capacity of your GPU?

**Comment by ChenHongruixuan** [comment]
Hi, Please refer to: https://www.nvidia.cn/data-center/a100/

**Comment by sasa550** [comment]
OK,  I realize I overlooked that point. Thank you for your response.
