### ISSUE TITLE
Is the model file of the second dataset available for download? Congratulations on your article being accepted!

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [ChenHongruixuan/MambaCD#56]
Congratulations

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you so much for your blessing! Thank you very much for your congratulations! The weights of MambaSCD will be uploaded this week. We'd appreciate it if you could give this repo a star and stay tuned!!

Best,

**Comment by ChenHongruixuan** [comment]
The weight of MambaSCD has been loaded. Feel free to use them :)
