### ISSUE TITLE
MouduleFoundError

### ISSUE THREAD

**Issue by yonadance** [ChenHongruixuan/MambaCD#58]
在使用./changedetection/scripts中的训练代码的时候报错：
`ModuleNotFoundError: No module named 'MambaCD.changedetection'
`
尝试将对应的py文件移到MamCD上一级文件进行运行，不再报错，但是否会对后续训练有影响呢？

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your interest to our work. If you have successfully loaded the pre-trained weight for the encoder, we assume that there is no effect on the training process. But it depends on the obtained final accuracy anyway. If there are follow-up questions, please leave a comment in this issue.

Best,

**Comment by JoyLinWQ** [comment]
> [yonadance](/yonadance)

Hi @yonadance , I had the same issue when following the instructions and running `python script/infer_MambaBCD.py ...` from `MambaCD/changedetection` folder.

Solution:
cd .. # running from one folder up
python changedetection/script/infer_MambaBCD.py ....

There will be several MambaCD packages error similar to below:
```
File "/home/jupyter/MambaCD/changedetection/models/MambaBCD.py", line 6, in <module>
    from MambaCD.changedetection.models.Mamba_backbone import Backbone_VSSM
ModuleNotFoundError: No module named 'MambaCD'
```
Rename all the import lines from `MambaCD.changedetection....` to `changedetection....`
