### ISSUE TITLE
NameError: name 'selective_scan_cuda_oflex' is not defined

### ISSUE THREAD

**Issue by gozy0** [ChenHongruixuan/MambaCD#59]
When I execute the infer_MambaBCD.py, I get the following error, where the 'selective_scan_cuda_oflex'  in vmamba.py is not defined:

project_dir/MambaCD/classification/models/vmamba.py", line 299, in forward
    out, x, *rest = selective_scan_cuda_oflex.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1, oflex)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'selective_scan_cuda_oflex' is not defined

I then downloaded the VMamba repo, and checked the corresponding vmamba.py under classification/models directory. There is no 'selective_scan_cuda_oflex' anymore.   Can you help with resolving this error? 

I would like to first run infer then move to training with your codes, however, I am stuck at the inference stage, as I described above.
Thank you

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your interest to our work. May I ask if you follow the instructions in the README file and finish the installation? You need to perform [cd kernels/selective_scan && pip install .] this first. 

Best,

**Comment by gozy0** [comment]
Thanks, yes I followed the instructions. However, I did not install VMamba. I think you already included required vmamba modules under classification folder? Could there be any step missing in your instructions, assuming that we do not do anything with the other git repo, i.e. the vmamba ?

**Comment by gozy0** [comment]
I re-did the whole sequence of instructions, and this time inference seems to be running but the performance is really low: with your vssm_tiny_224_0229flex model, on test set of the LEVIR-CD+ (images from train_638 to train_985), the calculated inference performance measures are: Racall rate is 0.11051257609596075, Precision rate is 0.05250886527089251, OA is 0.8825117637371195, F1 score is 0.0711917392007791, IoU is 0.036909702559693565, Kappa coefficient is 0.01688449906673563
These are at unacceptable levels, is this expected?

**Comment by ChenHongruixuan** [comment]
Are you sure you load the model successfully?? You can send all the log info so that we can determine the issue you met.

**Comment by gozy0** [comment]
Forgot to add: during both training and inference, I used the LEVIR_CD+ dataset. Would that work?

**Comment by gozy0** [comment]
I tried inference again with your suggested: --resume '../saved_model/MambaBCD_Tiny_LEVIRCD+_F1_0.8803.pth' option, in this case it gives reasonable results. It did not give reasonable results with the model that I trained.

**Comment by ChenHongruixuan** [comment]
Hi,

Yes, the F1 value of the result on LEVIR-CD+ should be 0.8803. Other peers have demonstrated that the code and files are fine.

**Please send the all log information** to us so that we can figure it out. We can't tell what problems you're having just by you giving this information.

Best,

**Comment by ChenHongruixuan** [comment]
Hi,

just the print output.

**Comment by gozy0** [comment]
I don't have the print out currently, as I ran the training overnight on a remote machine, however, the training finished without problems (I started from the model you suggested) and it saved the last model under the folder: MambaCD/changedetection/models/LEVIR-CD+/MambaBCD_Small_1725292912.8204563/9500_model.pth  Here is the command I used to train:  
python script/train_MambaBCD.py --dataset 'LEVIR-CD+' --batch_size 8 --crop_size 256 --max_iters 160000 --model_type MambaBCD_Small --model_param_path '/home/gozy/ MambaCD/changedetection/models' --train_dataset_path '/home/gozy/Dataset/train' --train_data_list_path '/home/gozy/Dataset/train.txt' --test_dataset_path '/home/gozy/Dataset/test' --test_data_list_path '/home/gozy/Dataset/test.txt' --cfg '/home/gozy/MambaCD/changedetection/configs/vssm1/vssm_small_224.yaml' --pretrained_weight_path '/home/gozy/MambaCD/pretrained_weight/vssm_small_0229_ckpt_epoch_222.pth'
--resume '/home/gozy/MambaCD/saved_model/MambaBCD_Tiny_LEVIRCD+_F1_0.8803.pth'

Then using the latest saved/trained model 9500_model.pth, I am running the inference by the following command, and the results are really bad (F1 score is 0.07837276096645185, IoU is 0.0407845805755065): 
python3 script/infer_MambaBCD.py  --dataset 'LEVIR-CD+' --model_type 'MambaBCD_Tiny' --test_dataset_path '/home/gozy/Dataset/test' --test_data_list_path '/home/gozy/Dataset/test.txt' --cfg '/home/gozy/MambaCD/changedetection/configs/vssm1/vssm_tiny_224_0229flex.yaml' --pretrained_weight_path '/home/gozy/MambaCD/changedetection/models/LEVIR-CD+/MambaBCD_Small_1725292912.8204563/9500_model.pth'

I can only get decent results when I do the inference with your provided model: MambaCD/saved_model/MambaBCD_Tiny_LEVIRCD+_F1_0.8803.pth. 
However, this is not okay because my goal is to be able re-train your model, and maybe later with other datasets. 
Note: I had to decrease the batchsize to 8 due to  memory requirements from the GPU.

**Comment by gozy0** [comment]
Hello, using the infer command with the --resume option, I was able to get decent results on the model that I trained. I will close this issue, and may open another one if I have further questions. Thanks very much for all your help.

**Comment by ChenHongruixuan** [comment]
Glad to hear that! If our code is useful for your research, please kindly considering to give this repo a star :)
