### ISSUE TITLE
I encounter following issue: "subprocess-exited-with-error"

### ISSUE THREAD

**Issue by chira98** [ChenHongruixuan/MambaCD#60]
```Processing /userhomes/17/CD/MambaCD/kernels/selective_scan
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/userhomes/17/CD/MambaCD/kernels/selective_scan/setup.py", line 139, in <module>
          ext_modules = get_ext()
        File "/userhomes/17/CD/MambaCD/kernels/selective_scan/setup.py", line 53, in get_ext
          raise RuntimeError(
      RuntimeError: package is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      
      torch.__version__  = 1.13.1
      
      
      
      
      CUDA_HOME = /usr
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by ChenHongruixuan** [comment]
Hi, thank you for your interest to our work! Please make sure the version of your pytorch and CUDA meet the requirement. 

Best,

**Comment by heikeyuhuajia** [comment]
> ```processing
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/userhomes/17/CD/MambaCD/kernels/selective_scan/setup.py", line 139, in <module>
>           ext_modules = get_ext()
>         File "/userhomes/17/CD/MambaCD/kernels/selective_scan/setup.py", line 53, in get_ext
>           raise RuntimeError(
>       RuntimeError: package is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
>       
>       
>       torch.__version__  = 1.13.1
>       
>       
>       
>       
>       CUDA_HOME = /usr
>       
>       
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> ```

Hi, the prompt is: RuntimeError: package is only supported on CUDA 11.6 and above. I had this problem before, upgrading **CUDA to 11.8** and reinstalling **torch-cuda11.8** solved it.

**Comment by ChenHongruixuan** [comment]
Hi,

You can also refer to the solution provided by @heikeyuhuajia 

Best,
