### ISSUE TITLE
About the VSS Block Internal Structure

### ISSUE THREAD

**Issue by heikeyuhuajia** [ChenHongruixuan/MambaCD#61]
Hi, I got some confusion while debugging, in class VSSBlock in vmamba.py, I found that the data flow seems to be: **‘input’->SSMBranc->‘x’->MLP branch**; but in the paper's diagram it seems to be: **(‘input’->SSMBranch->‘x1’) * (’ input‘->Linear->’x2")**, may I know if I write my own paper, should I follow the diagram or your code? Or am I setting something wrong that causes this result? The configuration file still uses your configuration.
![212871725251000_ pic](https://github.com/user-attachments/assets/5f9af3ed-13e4-47fa-be13-8017c6830d24)
![212911725251668_ pic](https://github.com/user-attachments/assets/f986c1d4-c3f2-4374-82cc-ee088c6fe44f)

**Comment by ChenHongruixuan** [comment]
Hi @heikeyuhuajia ,

Thank you so much for your question! 

What we have plotted here is the original VSS Block. However, the code and models in VMamab's repository are constantly being updated, so our code was updated once. If you are plotting the figure currently for your paper, it is recommended that you do so according to the current code. Please refer to the Figure 3 in current VMamba paper (https://arxiv.org/pdf/2401.10166).

Best,

**Comment by heikeyuhuajia** [comment]
Thank you very much for your answer, it helped me a lot and I will go back and read the new VSS block carefully!
