### ISSUE TITLE
Using Model for Semantic Change Detection with TIFF Images

### ISSUE THREAD

**Issue by Fatemeh90** [ChenHongruixuan/MambaCD#64]
Hi 

Thank you for your great code! I have two satellite images in TIFF format, and I would like to use your model to see the semantic change detection output. Could you please guide me on how to proceed with this?

Looking forward to your response.

Best regards

**Comment by ChenHongruixuan** [comment]
Hi @Fatemeh90 ,

You can just perform our code directly according to our instructions. The stuff you need to modify are to crop your images into small patches (like 256x256 or 512x512) and change the file suffix from .png to .tif in make_data_loader.py. 

Please kindly consider giving this repository a star if our code helps you in your research, thank you very much!

Best,
