### ISSUE TITLE
使用MambaBCD_Small_LEVIRCD进行infer结果无图像

### ISSUE THREAD

**Issue by Si1ive** [ChenHongruixuan/MambaCD#68]
'--resume', \MambaBCD_Small_LEVIRCD+_F1_0.8825.pth'
'--cfg', \MambaCD-master\changedetection\configs\vssm1\vssm_small_224.yaml'
已添加，但是输出结果经过np.argmax(output_1, axis=1)后变成了全0，所有结果都是这样
不添加预训练参数的话，可以生成类似于随机的黑白图像

**Comment by ChenHongruixuan** [comment]
Hi @Si1ive ,

Thank you for your interest to our work and your question. Are you sure you put our trained weight under the right folder? According to your code, it seems that you only provide the name of the file instead of its full path.

BTW, in order to find your specific issue, we recommend you upload the full print output.

Best,

**Comment by Si1ive** [comment]
Hi @ChenHongruixuan 
感谢您的回复
我的配置
parser.add_argument('--resume', type=str, default=r'F:\DMU\MambaCD-master\pretrained_weight\MambaBCD_Small_LEVIRCD+_F1_0.8825.pth')
parser.add_argument('--cfg', type=str, default=r'F:\DMU\MambaCD-master\changedetection\configs\vssm1\vssm_small_224.yaml')
我选取了一些数据进行infer，输出只有一些貌似不是要害的警告
=> merge config from F:\DMU\MambaCD-master\changedetection\configs\vssm1\vssm_small_224.yaml
F:\DMU\MambaCD-master\changedetection\utils_func\metrics.py:23: RuntimeWarning: invalid value encountered in scalar divide
  Pre = self.confusion_matrix[1, 1] / (self.confusion_matrix[0, 1] + self.confusion_matrix[1, 1])
Racall rate is 0.0, Precision rate is nan, OA is 0.9594736893971761, F1 score is nan, IoU is 0.0, Kappa coefficient is 0.0
Inference stage is done!
结果图像，图像全黑
![微信截图_20241006131049](https://github.com/user-attachments/assets/415e2d36-fb5f-4697-8134-5b49c8c77a8b)


如果我把参数去掉parser.add_argument('--resume', type=str)
输出
=> merge config from F:\DMU\MambaCD-master\changedetection\configs\vssm1\vssm_small_224.yaml
Racall rate is 0.630826432181104, Precision rate is 0.038851767540863544, OA is 0.3525882562001546, F1 score is 0.07319551961496713, IoU is 0.03798803685589338, Kappa coefficient is -0.0034155665081370703
Inference stage is done!
生成的图像
![1728191243860](https://github.com/user-attachments/assets/48d54898-df24-47f6-bf0d-1e4c8f952c8d)

**Comment by ChenHongruixuan** [comment]
Hi @Si1ive ,

First, please make sure the trained weight has been loaded successfully. Secondly, did you perform the experiment on your own data or on LEVIR-CD+ data? 

Best,

**Comment by ChenHongruixuan** [comment]
Hi @Si1ive ,

May I ask did you solve the issue? 

Best,
