### ISSUE TITLE
I encounter a question！

### ISSUE THREAD

**Issue by whw2021** [ChenHongruixuan/MambaCD#7]
Hello, author. When I run the BCD code, I encounter an error: torch.cuda.OutOfMemoryError: CUDA out of memory. So, I wanted to ask how much GPU memory is required to run this part of the code?

**Comment by ChenHongruixuan** [comment]
Hi, 

Thank you so much your interest to our work. 

What is the model of your graphics card? If the current memory usage is too high, you can lower the batch size to run the code. According to our previous experiments, this will not affect the final accuracy too much.

Best,

**Comment by whw2021** [comment]
Okay, I understand, thank you. Additionally, the graphics card model I'm using is the NVIDIA RTX A6000.

**Comment by ChenHongruixuan** [comment]
> I'm using is the NVIDIA RTX A6000
Then I'm pretty sure you can run our method 😂 try lowering the batch size.
