### ISSUE TITLE
About the visualization of features.

### ISSUE THREAD

**Issue by NUAAZJY** [ChenHongruixuan/MambaCD#70]
Hello, I would like to draw a heatmap similar to Fig.14 in your paper, but I did not see the corresponding script in the project file. May I ask if this script can be open sourced? Thank you very much.
![Uploading 6c498ce4-aa4e-4c1c-adb7-7e2477c3ca4e.png…]()

**Comment by ChenHongruixuan** [comment]
Hi @NUAAZJY ,

Thank you for your question. You can just simply add up the channels of the feature map and normalise them. Then use libraries such as OpenCV for colouring.

Best,
