### ISSUE TITLE
请问 xBD数据集的以下代码是否存在问题？

### ISSUE THREAD

**Issue by DevKPro** [ChenHongruixuan/MambaCD#71]
在 xBD 数据集加载的代码中，存在以下代码段：
`if 'train' in self.data_pro_type: 
            parts = self.data_list[index].rsplit('_', 2)

            pre_img_name = f"{parts[0]}_pre_disaster_{parts[1]}_{parts[2]}.png"
            post_img_name = f"{parts[0]}_post_disaster_{parts[1]}_{parts[2]}.png"

            pre_path = os.path.join(self.dataset_path, 'images', pre_img_name)
            post_path = os.path.join(self.dataset_path, 'images', post_img_name)
            
            loc_label_path = os.path.join(self.dataset_path, 'masks', pre_img_name)
            clf_label_path = os.path.join(self.dataset_path, 'masks', post_img_name)`
这段代码按 “-” 对文件名切割，但按照 xview 下载的文件解压后是没有符合的文件名称，请问作者是怎么处理文件名的？

**Comment by lee1235896** [comment]
同样的问题，请问你找到答案了吗？

**Comment by ChenHongruixuan** [comment]
Hi @lee1235896 @DevKPro ,

The code I uploaded was for our experiments. You can very simply modify it to a form that reads images based on the name of the images in the original xBD dataset. We will upload the modified script today or tomorrow.

Best,

**Comment by lee1235896** [comment]
Thank you for your reply!

**Comment by ChenHongruixuan** [comment]
Hi @lee1235896 @DevKPro ,

Since we don't know how you record the names of images in your case, we think it is a bit difficult to upload a unified solution. Please just modify the current loading code according to the organization of your xBD dataset and image names. 

Best,

**Comment by lee1235896** [comment]
I have already modified the loading code and solved the problem.Many thanks!

**Comment by DevKPro** [comment]
> Hi @lee1235896 @DevKPro ,
> 
> Since we don't know how you record the names of images in your case, we think it is a bit difficult to upload a unified solution. Please just modify the current loading code according to the organization of your xBD dataset and image names.
> 
> Best,

I have already solved the problem according to your suggestion. Thank you very much.
