### ISSUE TITLE
About Training Logs

### ISSUE THREAD

**Issue by DevKPro** [ChenHongruixuan/MambaCD#72]
Dear author,
Thank you very much for sharing your open-source code. I would like to inquire about the possibility of sharing the training logs of the model. I am interested in examining the training logs to gain insights into the model's convergence behavior.

**Comment by ChenHongruixuan** [comment]
Hi,

Which training log file (which model on which dataset) do you want? We can try to find it/them for you in our server. 

Best,

**Comment by DevKPro** [comment]
> Hi,
> 
> Which training log file (which model on which dataset) do you want? We can try to find it/them for you in our server.
> 
> Best,

Thank you for your reply. I would like to request the training logs of the MambaBDA model on xview2 and the MambaBCD model on the LEVIR-CD+ dataset. I wish you a happy life!

**Comment by ChenHongruixuan** [comment]
Hi @DevKPro ,

Could you send your email to us.

**Comment by DevKPro** [comment]
> Hi @DevKPro ,
> 
> Could you send your email to us.

My email is 748207458@qq.com. Thank you again for sharing your valuable data and for your patient replies. Wish you all the best!
