### ISSUE TITLE
Duplicate between LEVIRCD and LEVIRCD+

### ISSUE THREAD

**Issue by kirin-from-16** [ChenHongruixuan/MambaCD#73]
Hi, i just want to know if LEVIRCD + has any overlap regions with LEVIRCD dataset. If it does , how many percent are overlapped? What are the differences between it with LEVIRCD?

Thank you.

**Comment by ChenHongruixuan** [comment]
Hi @kirin-from-16 ,

Thank you for your question! LEVIR-CD can be seen as a subset of LEVIR-CD+. All images in LEVIR-CD are included in LEVIR-CD+. Compared to LEVIR-CD, LEVIR-CD+ is a more difficult dataset. 

Best,
