### ISSUE TITLE
Three tasks at once 

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [ChenHongruixuan/MambaCD#76]
Can input a set of images and produce the results of three tasks, or the results of scd and bda, instead of running it three times, and feel that there are features that can be reused, which can save a lot of time

**Comment by ChenHongruixuan** [comment]
Hi @kuaiqushangzixiba ,

Thank you so much for your suggestion. This is certainly possible and you can try it yourself to see whether the better results can be yielded.

Best,
