### ISSUE TITLE
Regarding the train and validation split for SCD task on SECOND dataset

### ISSUE THREAD

**Issue by Essha123** [ChenHongruixuan/MambaCD#77]
Hello, 

I was wondering have you used test dataset for validation while training the SCD network? and then evaluated on the same dataset? If not then can you please let me know what was the split ratio between training and validation sets, or which set on images were used for validation? 

Looking forward to hearing from you soon.

Thank you

**Comment by ChenHongruixuan** [comment]
Hi @Essha123 ,

Thank you for your interest in our works! Please refer to [issue 66](https://github.com/ChenHongruixuan/MambaCD/issues/66).

Best
