### ISSUE TITLE
可否使用C++程序，部署到边缘设备Jetson上？

### ISSUE THREAD

**Issue by retioa11** [ChenHongruixuan/MambaCD#78]
正在研究在Jetson上做医疗影像的变化检测，用我们这个库训练的模型，有没有在Jetson上被Tensorrt调用的技术路径？ 可以转换为通用的onnx格式吗？ 如果可以，那说不定有戏。

**Comment by ChenHongruixuan** [comment]
hi @retioa11 ,

thank you so much for your question. Now, we do not have the plan to extend ChangeMamba to medical images or Jetson. The effectiveness of ChangeMamba in remote sensing change detection has been demostrated. If you can extend it to medical images and prove its effectiveness, we'd really appreciate it. 

Best,

**Comment by retioa11** [comment]
Ok.
