### ISSUE TITLE
Question about MambaBDA

### ISSUE THREAD

**Issue by huakaifuguilaolaifu** [ChenHongruixuan/MambaCD#80]
作者您好，xBD数据集里除了Non-Damage, Minor Damage, Major Damage, and Destroyed，还有一些实例没有分类标签，请问您是怎么处理这些样本的呢？

**Comment by ChenHongruixuan** [comment]
Hi,

Thank you for your question. We assigned these pixels directly to 255 without involving in training process.

Best,
