### ISSUE TITLE
WHU-CD的下载链接打不开，可否帮忙看一下？

### ISSUE THREAD

**Issue by retioa11** [ChenHongruixuan/MambaCD#81]
点击ReadMe中的[WHU-CD](https://study.rsgis.whu.edu.cn/pages/download/building_dataset.html)下载链接，打不开，返回502的错误，如下图所示，可否提供下百度网盘或者其他可以用的下载链接？
![image](https://github.com/user-attachments/assets/628028a2-f511-42be-98d6-fa8ac707adeb)

**Comment by ChenHongruixuan** [comment]
please refer to this url: http://[gpcv.whu.edu.cn/data/building_dataset.html](http://gpcv.whu.edu.cn/data/building_dataset.html)
