### ISSUE TITLE
The Mamba parameter problem

### ISSUE THREAD

**Issue by henuJackSon** [ChenHongruixuan/MambaCD#85]
Hello.
1. During the training process, Mamba acts as the encoder, will its parameters be updated continuously during the training process? Or will the parameters freeze?
2. The application of this article on 3 tasks, is each task separately trained? That is, the encoders for each task are independent with different parameters
Looking forward to your recovery
Thank you very much

**Comment by ChenHongruixuan** [comment]
Hi @henuJackSon ,

Thanks a lot for your interest to our work! 

> During the training process, Mamba acts as the encoder, will its parameters be updated continuously during the training process? Or will the parameters freeze?

Yes. Its parameters will be updated during the training process. 

> The application of this article on 3 tasks, is each task separately trained? That is, the encoders for each task are independent with different parameters

Yes. They are trained separately. 

Best,
