### ISSUE TITLE
BCD Evaluation Metrics RuntimeWarning: invalid value encountered in scalar divide

### ISSUE THREAD

**Issue by JoyLinWQ** [ChenHongruixuan/MambaCD#86]
Hi @ChenHongruixuan  , I'm encountering the following error due to zeros in the confusion matrix when running on my own images.

CM:  [[29900574.  1556706.]
 [       0.        0.]]

```
/home/jupyter/MambaCD/changedetection/utils_func/metrics.py:25: RuntimeWarning: invalid value encountered in scalar divide
  Rec = self.confusion_matrix[1, 1] / (self.confusion_matrix[1, 0] + self.confusion_matrix[1, 1])
Rec:  nan
Pre:  0.0
F1:  nan
Racall rate is nan, Precision rate is 0.0, OA is 0.9505136489868165, F1 score is nan, IoU is 0.0, Kappa coefficient is 0.0
Inference stage is done!
```

When running the LEVIR-CD+ dataset, i can get the following:
```
CM:  [[1.26982791e+08 3.97602000e+05]
 [3.46063000e+05 6.49127200e+06]]
Rec:  0.9493862740380572
Pre:  0.942283455902953
F1:  0.9458215301836073
Racall rate is 0.9493862740380572, Precision rate is 0.942283455902953, OA is 0.9944592639803886, F1 score is 0.9458215301836073, IoU is 0.8972119591366172, Kappa coefficient is 0.9429019112092241
Inference stage is done!
```

What could be the problem with my own dataset?

I've ensured that i have:
- T1 images
- T2 images
- GT (white 255 polygons with black 0 background) - T1 building masks in greyscale, without alpha channel
- All images are in 1024x1024 
- binary change map range is 0-1, and after `binary_change_map[binary_change_map==1] = 255` it is 0-255.
- decent output prediction masks.

Any help is appreciated. Thanks.

**Comment by ChenHongruixuan** [comment]
Hi @JoyLinWQ ,

It seems that all pixels are predicted to have a value of 0. I think you need to check the following: first, check whether our trained weights have been loaded successfully; second, the format of your dataset needs to be consistent with LEIVIR-CD+ (e.g., the value of the changed pixel needs to be 255, not 1); finally, can you show us some examples of your dataset? This way we can better help analyze the cause.

Best,

**Comment by JoyLinWQ** [comment]
Hi @ChenHongruixuan , 

1. Trained weights have been loaded successfully.
2. Format of dataset is consistent with LEVIR-CD+, value of changed pixel is 255 as shown in printout below.
3. Examples of my dataset:
Set 1 (change detected):
T1 ![17_103361_65046](https://github.com/user-attachments/assets/0f1d6cb6-c6c5-4968-8593-d844372d45d2)
T2 ![17_103361_65046](https://github.com/user-attachments/assets/41efed0e-0e88-4311-bb45-1f51f3497b70)
Label ![17_103361_65046](https://github.com/user-attachments/assets/9f7b76e2-d143-40be-9095-b23db9a12df2)
Output ![17_103361_65046](https://github.com/user-attachments/assets/511fa294-6c9c-4e45-b4eb-d0b349c626e4)

Set 2 (no change detected): 
T1 ![17_103364_65048](https://github.com/user-attachments/assets/3b8c78f2-fdc2-4ba7-85de-e59a2d6c509e)
T2 ![17_103364_65048](https://github.com/user-attachments/assets/4916861e-7a92-4829-8830-bea8b5e0dd60)
Label ![17_103364_65048](https://github.com/user-attachments/assets/b2df94fd-b0fe-4b4f-8753-19e1a3f43196)
Output ![17_103364_65048](https://github.com/user-attachments/assets/e07bf63b-d9a5-452b-a3eb-c8453982966c)


I also tried printing out the output min and max values below. Do u find anything unusual? What could be the cause of the zeros in the confusion matrix? Could we re-open this issue?

For my dataset (some has no change detected, which is correct):
```
pre post change imgs:  tensor(-1.1589, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-1.6213, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -9.3004 9.261008
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-1.8044, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-1.4843, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -8.996285 9.222573
output argmax:  0 0
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 0
pre post change imgs:  tensor(-1.3130, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-1.5185, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -8.9506035 8.477517
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-1.3004, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-1.5528, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -9.991187 9.20331
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-1.1779, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-1.4843, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -9.021376 8.408981
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
```

For LEVIR-CD+:
```
pre post change imgs:  tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -11.029644 10.620077
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-1.7069, device='cuda:0') tensor(2.2217, device='cuda:0') tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -13.036368 11.239271
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -13.958538 14.809068
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0') tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -11.884417 11.629654
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
pre post change imgs:  tensor(-2.0152, device='cuda:0') tensor(2.5006, device='cuda:0') tensor(-2.1179, device='cuda:0') tensor(2.6400, device='cuda:0')
output:  -11.362786 10.983093
output argmax:  0 1
GT, Pre: (1, 1024, 1024) (1, 1024, 1024)
Binary change map:  0 255
```
