### ISSUE TITLE
vmamba预训练模型

### ISSUE THREAD

**Issue by adleess** [ChenHongruixuan/MambaCD#87]
python script/train_MambaSCD.py --dataset 'SECONDMINI' \
                                --batch_size 4 \
                                --crop_size 256 \
                                --max_iters 800000 \
                                --model_type MambaSCD_Small \
                                --model_param_path './saved_models' \
                                --train_dataset_path './datasets/data_name_list/SECONDMINI/train' \
                                --train_data_list_path './datasets/data_name_list/SECONDMINI/train_list.txt' \
                                --test_dataset_path './datasets/data_name_list/SECONDMINI/test' \
                                --test_data_list_path './datasets/data_name_list/SECONDMINI/test_list.txt' \
                                --cfg './configs/vssm1/vssm_small_224.yaml' \
                                --pretrained_weight_path './pretrained_weight/vssm_small_0229_ckpt_epoch_222.pth'
在指定model_type MambaSCD_Small，以及下载了对应了预训练权重后，进行训练，出现以下提示
=> merge config from ./configs/vssm1/vssm_small_224.yaml
Successfully load ckpt ./pretrained_weight/vssm_small_0229_ckpt_epoch_222.pth
_IncompatibleKeys(missing_keys=['outnorm0.weight', 'outnorm0.bias', 'outnorm1.weight', 'outnorm1.bias', 'outnorm2.weight', 'outnorm2.bias', 'outnorm3.weight', 'outnorm3.bias'], unexpected_keys=['classifier.norm.weight', 'classifier.norm.bias', 'classifier.head.weight', 'classifier.head.bias'])
False

这是表明我预训练权重和模型没匹配上吗

**Comment by ChenHongruixuan** [comment]
Hi @adleess ,

The weights have been loaded on. There are just a couple of norm layers that aren't loaded on. This is due to the original VMamba ckpt not matching the code since VMamba has previously been updating the network structure. The fact that these layers are not loaded does not affect the detection results.

Best

**Comment by adleess** [comment]
> Hi @adleess ,
> 
> The weights have been loaded on. There are just a couple of norm layers that aren't loaded on. This is due to the original VMamba ckpt not matching the code since VMamba has previously been updating the network structure. The fact that these layers are not loaded does not affect the detection results.
> 
> Best

Thank you for your reply !  I have another question .In SCD I would like to use my own private dataset, can you please tell me how the GT_CD in the Second dataset you are using was made?

**Comment by ChenHongruixuan** [comment]
Hi @adleess ,

It was just generated using the semantic (land-cover) maps of pre-change and post-change images.

Best,
