### ISSUE TITLE
Mamba BDA

### ISSUE THREAD

**Issue by earnestworthing** [ChenHongruixuan/MambaCD#88]
Dear author,

As described within https://github.com/ChenHongruixuan/MambaCD/issues/83#issue-2730798848 I am currently not able to run your BDA code. Since I noticed that in the README you are using the train_MambaSCD.py for the BDA instead of train_MambaBDA.py I was wandering whether this is intended. When I try to use train_MambaSCD.py I run into the error
`File "user/MambaCD/changedetection/script/train_MambaSCD.py", line 102, in training
    pre_change_imgs, post_change_imgs, label_cd, label_clf_t1, label_clf_t2, _ = data`
since label_cd is not provided by the DamageAssessmentDatset.

Thank you for your clarification in advance.

**Comment by ChenHongruixuan** [comment]
Hi @earnestworthing ,

Thank you for your question. 

>  Since I noticed that in the README you are using the train_MambaSCD.py for the BDA instead of train_MambaBDA.py I was wandering whether this is intended. 

This was our mistake. The script for the Building damage assessment task is train_MambaBDA, not train_MambaSCD. We have modified it. Thank you for your kind reminder. 

BTW, we have answered your issue 83. You could go to take a look. 

Best,
