### ISSUE TITLE
语义变化检测推理时使用预训练权重报错

### ISSUE THREAD

**Issue by adleess** [ChenHongruixuan/MambaCD#89]
![image](https://github.com/user-attachments/assets/f3bee94b-25d2-4ce2-9981-250bf0a8d5c1)

**Comment by ChenHongruixuan** [comment]
Hi @adleess ,

Thank you for your question. The problem is caused by the different number of categories. The output dimension of the classifier in the last layer of the model trained on SECOND dataset is 7, and you changed it to 18, which caused the error. 

Best,
