### ISSUE TITLE
XBD TRAINING : Need guidance

### ISSUE THREAD

**Issue by koleshjr** [ChenHongruixuan/MambaCD#90]
Hello,
First of all this is a very interesting project and thank you for open sourcing your work.

I am trying to understand the BDA training pipeline using the official released xview dataset.

The targets provided in the xview dataset are blank png images example attached below
![image](https://github.com/user-attachments/assets/083b603e-0b54-48e4-868a-42f27233c63e)

So my immediate understanding is this is not right and I have to use the json labels to create the masks for localization and classification as well. For localization it is supposed to be a 2d binary image for example where white pixels mask the buildings and the black ones representing the background.

And for the classification labels we can use multiple colors for each building mask to represent the damage category e,g red for major-damage, blue for minor_damage etc and these processed images are what we load for training? not the blank ones right?

Now in the dataloader code we have:

        loc_label = self.loader(loc_label_path)[:,:,0]
        clf_label = self.loader(clf_label_path)[:,:,0]
       
meaning we are taking the first channel for each image as the labels. So I just can't find where the labels are converted to class indices in the data loader for classification labels. Maybe my understanding for the images to be loaded is wrong but I think I need to convert the first channel pixels to class indices for the given damage classes?

Please guide me , Thank you

**Comment by koleshjr** [comment]
never mind I have figured it out, really cool project btw

**Comment by ChenHongruixuan** [comment]
@koleshjr ,

Thank you so much for your interest to our work! 

> never mind I have figured it out, really cool project btw

Glad to hear that :)

Best,

**Comment by CrazyuserNova** [comment]
> never mind I have figured it out, really cool project btw
I encounter the same problem. How do you solve it
