### ISSUE TITLE
您提供的处理好的SECOND数据集中CD标签的问题

### ISSUE THREAD

**Issue by yokii89** [ChenHongruixuan/MambaCD#91]
**您好，
       在使用您处理的SECOND数据集中CD的标签时，我查看了所有CD标签，发现只有【0，255】这两个值。所以我猜测其中0表示未变化区域，255表示变化区域。
       但是在BCD代码上，您使用了ignore_index==255 , 难道255表示未标记区域么，那么标签应该中应该是【0，1，255】啊。
期待您的解惑**
![微信截图_20241221104807](https://github.com/user-attachments/assets/9e9a7c1a-eddc-4715-8ec3-01d333018d47)

**Comment by ChenHongruixuan** [comment]
Hi @yokii89 ,

Thank you so much for your interest to our work! Please take a look at the dataloader. We divide the GT_CD to 255 so that the changed pixels' value is 1.

Best,
